
CREATE TABLE aircraftDetails (aircraft_number INT,
							  aircraft_assigned_airline VARCHAR(100),
							  aircraft_photo VARCHAR(200),
							  aircraft_web_link VARCHAR(200),
							  aircraft_type VARCHAR(100),
							  aircraft_serial_number INT,
							  aircraft_registration_code VARCHAR(20),
							  aircraft_manufactured_date Date,
							  aircraft_country_of_registration VARCHAR(50),
							  aircraft_country_of_registration_flag VARCHAR(300),
							  aircraft_icao_twenty_four_bit_address VARCHAR(10),
							  aircraft_size VARCHAR(50),
							  aircraft_wing_type VARCHAR(50),
							  aircraft_fuel_capacity INT,
							  aircraft_has_anti_icing_and_de_icing_systems VARCHAR(5),
							  aircraft_max_altitude INT,
							  aircraft_max_cruising_speed INT,
							  aircraft_max_travel_range_without_refueling INT
							 );

INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (1,'Qantas Airways ','https://cdn.jetphotos.com/full/6/45630_1668662049.jpg','https://www.jetphotos.com/photo/10783717','Airbus A380-842',22,'VH-OQC','2008-12-29','Australia ','https://www.cia.gov/the-world-factbook/static/e439ba7cc4d23605ec27b6dfff536d46/f0719/AS-flag.jpg','7FFFFF','Large Aircraft ','Low-Wing',82000,'Yes ',43100,1041,15200);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (2,'LATAM Airlines ','https://cdn.jetphotos.com/full/6/756487_1677248860.jpg','https://www.jetphotos.com/photo/10890073','Boeing 787-9 Dreamliner ',35322,'CC-BGD','2016-05-05','Chile','https://www.cia.gov/the-world-factbook/static/114fc978ce49b31147d43051cfeecb44/25252/CI-flag.jpg','E80FFF','Large Aircraft ','Swept-Wing',35528,'Yes ',43100,903,13620);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (3,'Garuda Indonesia Airlines ','https://cdn.jetphotos.com/full/5/555626_1680674172.jpg','https://www.jetphotos.com/photo/10930024','Boeing 737-8U3',38074,'PK-GMV','2012-04-14','Indonesia ','https://www.cia.gov/the-world-factbook/static/fd4f8e191bebbb77d483cfb362eca500/f0719/ID-flag.jpg','8A7FFF','Medium Sized Aircraft','Swept-Wing',5535,'Yes ',41000,850,6570);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (4,'Ethiopian Airlines ','https://cdn.jetphotos.com/full/5/65280_1642686990.jpg','https://www.jetphotos.com/photo/10459082','Boeing 787-8 Dreamliner ',34498,'ET-ATK','2016-07-29','Ethiopia ','https://www.cia.gov/the-world-factbook/static/9c1b2f5839f38b843aceebc5c3675116/f0719/ET-flag.jpg','040FFF','Large Aircraft ','Swept-Wing',33528,'Yes ',43100,903,13620);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (5,'Finnair Airlines ','https://cdn.jetphotos.com/full/5/753502_1678697736.jpg','https://www.jetphotos.com/photo/10908696','ATR 72-212A(500) ',769,'OH-ATH','2007-11-15','Finland ','https://www.cia.gov/the-world-factbook/static/06850042f7aae57d6098ff8cae5841d1/3df66/FI-flag.jpg','467FFF','Medium Sized Aircraft','High-Wing ',1680,'Yes ',25000,463,1530);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (6,'Air France ','https://cdn.jetphotos.com/full/6/906473_1676660321.jpg','https://www.jetphotos.com/photo/10865338','Airbus A340-311',78,'F-GLZH','1995-07-18','France ','https://www.cia.gov/the-world-factbook/static/85f69ee9a17f3261e1af5654de8da8c2/f0719/FR-flag.jpg','3BFFFF','Large Aircraft ','Swept-Wing',36624,'Yes ',41300,885,12900);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (7,'Vistara Airlines','https://cdn.jetphotos.com/full/5/82008_1672848265.jpg','https://www.jetphotos.com/photo/10838638','Boeing 787-9 Dreamliner ',66526,'VT-TSD','2020-02-28','India ','https://www.cia.gov/the-world-factbook/static/d7b06c1c42f902bb4d62554008d33c10/25252/IN-flag.jpg','83FFFF','Large Aircraft ','Swept-Wing',35528,'Yes ',43100,903,13620);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (8,'Caribbean Airlines ','https://cdn.jetphotos.com/full/6/1200647_1679887755.jpg','https://www.jetphotos.com/photo/10921582','Boeing 737-8',876,'9Y-JAM','2018-06-20','Jamaica ','https://www.cia.gov/the-world-factbook/static/3c94dc8783f5e709ef2e7b8b67aa6a1e/f0719/JM-flag.jpg','0BEFFF','Large Aircraft ','Swept-Wing',6820,'Yes ',41000,966,5765);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (9,'South African Airways','https://cdn.jetphotos.com/full/6/1700209_1679032121.jpg','https://www.jetphotos.com/photo/10912094','Airbus A330-243',5956,'ZS-SZC','2012-08-28','South Africa ','https://www.cia.gov/the-world-factbook/static/2b2e8dcc380d959e1065fa9ac8a1e0fb/f0719/SF-flag.jpg','00FFFF','Medium Sized Aircraft','Swept-Wing',25765,'Yes ',41000,903,13094);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (10,'Tarom Airlines ','https://cdn.jetphotos.com/full/6/970241_1680716303.jpg','https://www.jetphotos.com/photo/10930525','Airbus A318-111',2955,'YR-ASB','2006-12-04','Romania','https://www.cia.gov/the-world-factbook/static/050e69ddee88b218a97f4b49b43323f0/f0719/RO-flag.jpg','4A7FFF','Small Aircraft','Swept-Wing',6400,'Yes ',41000,828,5740);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (11,'Copa Airlines ','https://cdn.jetphotos.com/full/5/41380_1634331439.jpg','https://www.jetphotos.com/photo/10344137','Boeing 737 MAX 9',9901,'HP-9901CMP','2018-10-28','Panama','https://www.cia.gov/the-world-factbook/static/6fe42c1c78e9e96aa2943c5dceeee092/25252/PM-flag.jpg','0C2FFF','Large Aircraft ','Low-Wing',4299,'Yes ',41000,1012,5700);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (12,'Qatar Airways ','https://cdn.jetphotos.com/full/5/1106581_1677735452.jpg','https://www.jetphotos.com/photo/10896476','Airbus A350-941 ',12,'A7-ALH','2016-03-07','Qatar','https://www.cia.gov/the-world-factbook/static/d2635ab8cb20d8ee37a5f9b8266aab6b/f0719/QA-flag.jpg','06A3FF','Large Aircraft ','Low-Wing',41948,'Yes ',41500,950,15372);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (13,'Singapore Airlines ','https://cdn.jetphotos.com/full/6/63804_1674744832.jpg','https://www.jetphotos.com/photo/10862113','Boeing 747-412F(SCD)',32902,'9V-SFP','2005-10-19','Singapore','https://www.cia.gov/the-world-factbook/static/a6f920ab1a16dc27a79779a7fdce8cc9/596f3/SN-flag.jpg','76FFFF','Large Aircraft ','Swept-Wing',57285,'Yes ',45100,982,13449);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (14,'Caribbean Airlines ','https://cdn.jetphotos.com/full/5/25987_1674076235.jpg','https://www.jetphotos.com/photo/10854576','ATR 72-600 ',973,'9Y-TTB','2011-12-16','Trinidad And Tobago','https://www.cia.gov/the-world-factbook/static/92876418872953b9e9d93079073b60ee/80636/TD-flag.jpg','0C6FFF','Medium Sized Aircraft','High-Wing ',1666,'Yes ',25000,463,1530);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (15,'Turkish Airlines ','https://cdn.jetphotos.com/full/6/43669_1669056146.jpg','https://www.jetphotos.com/photo/10788529','Boeing 787-9 Dreamliner ',65801,'TC-LLA','2019-06-25','Turkey','https://www.cia.gov/the-world-factbook/static/f203364929f328df906f3043fdd71d49/f0719/TU-flag.jpg','4BFFFF','Large Aircraft ','Swept-Wing',35528,'Yes ',43100,903,13620);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (16,'Delta Airlines ','https://cdn.jetphotos.com/full/5/36424_1617937389.jpg','https://www.jetphotos.com/photo/10131898','Boeing 767-332',23435,'N121DE','1987-03-08','United States Of America ','https://www.cia.gov/the-world-factbook/static/730303882b8328fe4445b5d82cb93151/04372/US-flag.jpg','AFFFFF','Large Aircraft ','Low-Wing',23980,'Yes ',43100,858,11070);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (17,'American Airlines ','https://cdn.jetphotos.com/full/5/96575_1658161439.jpg','https://www.jetphotos.com/photo/10654399','Douglas DC-3',15432,'N400MF','1935-12-17','United States Of America ','https://www.cia.gov/the-world-factbook/static/730303882b8328fe4445b5d82cb93151/04372/US-flag.jpg','AFFFFF','Small Aircraft','Low-Wing',800,'No',20800,308,2406);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (18,'American Airlines ','https://cdn.jetphotos.com/full/6/93688_1653244805.jpg','https://www.jetphotos.com/photo/10581531','Lockheed L-188 Electra',1116,'N404GN','1960-12-06','United States Of America ','https://www.cia.gov/the-world-factbook/static/730303882b8328fe4445b5d82cb93151/04372/US-flag.jpg','AFFFFF','Small Aircraft','Low-Wing',1000,'No',30000,600,3541);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (19,'Copa Airlines ','https://cdn.jetphotos.com/full/5/795340_1678166810.jpg','https://www.jetphotos.com/photo/10902358','Boeing 737-7V3',33706,'HP-1525CMP','2004-06-09','Panama','https://www.cia.gov/the-world-factbook/static/6fe42c1c78e9e96aa2943c5dceeee092/25252/PM-flag.jpg','0C2FFF','Large Aircraft ','Swept-Wing',6875,'Yes ',41000,839,5575);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (20,'Conviasa Airlines','https://cdn.jetphotos.com/full/5/689431_1676877532.jpg','https://www.jetphotos.com/photo/10886011','Embraer E190-100',19000485,'YV2966','2014-10-20','Venezuela ','https://www.cia.gov/the-world-factbook/static/60089e42cfbc224bc8f185e22772c5e9/212d8/VE-flag.jpg','0DFFFF','Small Aircraft','Swept-Wing',4234,'Yes ',41000,850,4937);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (21,'Aerolíneas Argentinas','https://cdn.jetphotos.com/full/6/959960_1678026662.jpg','https://www.jetphotos.com/photo/10900465','Boeing 737-76N',32676,'LV-BZO','2009-06-25','Argentina ','https://www.cia.gov/the-world-factbook/static/e64d30d80d615e05173974bbb57b830c/ded98/AR-flag.jpg','E3FFFF','Large Aircraft ','Swept-Wing',25765,'Yes ',41000,950,15094);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (22,'LATAM Airlines ','https://cdn.jetphotos.com/full/6/2018446_1680721416.jpg','https://www.jetphotos.com/photo/10930563','Boeing 787-9 Dreamliner ',38468,'CC-BGN','2017-08-01','Brazil','https://www.cia.gov/the-world-factbook/static/0110ec84306ce8a2177b6306732d8d06/fc56b/BR-flag.jpg','E7FFFF','Large Aircraft ','Swept-Wing',35528,'Yes ',41000,903,13620);
INSERT INTO aircraftDetails (aircraft_number,aircraft_assigned_airline,aircraft_photo,aircraft_web_link,aircraft_type,aircraft_serial_number,aircraft_registration_code,aircraft_manufactured_date,aircraft_country_of_registration,aircraft_country_of_registration_flag,aircraft_icao_twenty_four_bit_address,aircraft_size,aircraft_wing_type,aircraft_fuel_capacity,aircraft_has_anti_icing_and_de_icing_systems,aircraft_max_altitude,aircraft_max_cruising_speed,aircraft_max_travel_range_without_refueling) VALUES (23,'Saudia (Saudi Arabian Airlines)','https://cdn.jetphotos.com/full/6/431771_1680582926.jpg','https://www.jetphotos.com/photo/10928901','Airbus A320-214',8070,'HZ-AS66','2019-12-01','Saudi Arabia ','https://www.cia.gov/the-world-factbook/static/253a2ad8e062a858fe6ed6d90bb18035/25252/SA-flag.jpg','717FFF','Large Aircraft ','Swept-Wing',6303,'Yes ',41000,810,6100);
